SELECT EMPLOYER_NAME, SOC_NAME, WORKSITE, AVG(PREVAILING_WAGE), COUNT(id) AS NumApps
FROM h1bdata.data
WHERE YEAR = 2016 AND WORKSITE is not NULL
GROUP BY WORKSITE, SOC_NAME, EMPLOYER_NAME
ORDER BY NumApps DESC;
